# Use postgres/example user/password credentials
version: '3.1'

services:

  populate:
    build: .
    environment:
      DB_URI: ${DB_URI}
    command: ["python", "main.py"]
    depends_on:
      - db

  app:
    build: .
    ports:
      - "8000:80"
    environment:
      DB_URI: ${DB_URI}
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: database
    ports:
      - 5432:5432
