"""Add table SensorData

Revision ID: 15d81fecb674
Revises: cfb29ad3ba02
Create Date: 2023-11-08 18:20:47.206127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d81fecb674'
down_revision: Union[str, None] = 'cfb29ad3ba02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.Column('irradiation', sa.Integer(), nullable=True),
    sa.Column('module_temperature', sa.Integer(), nullable=True),
    sa.Column('ambient_temperature', sa.Integer(), nullable=True),
    sa.Column('wind_velocity', sa.Float(), nullable=True),
    sa.Column('insolation', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('etotal_C', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('sensor_id', 'read_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_data')
    # ### end Alembic commands ###
