"""Correction in SensorData

Revision ID: 670eb6098be7
Revises: ba42bdecb96c
Create Date: 2023-12-12 16:59:33.296468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670eb6098be7'
down_revision: Union[str, None] = 'ba42bdecb96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('etotal_c', sa.Integer(), nullable=True))
    op.drop_column('sensor_data', 'etotal_C')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('etotal_C', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('sensor_data', 'etotal_c')
    # ### end Alembic commands ###
