"""Inverter new params

Revision ID: ba42bdecb96c
Revises: 78f852757b94
Create Date: 2023-12-07 16:53:14.480447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba42bdecb96c'
down_revision: Union[str, None] = '78f852757b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inverter_data', sa.Column('iac1', sa.Integer(), nullable=True))
    op.add_column('inverter_data', sa.Column('iac2', sa.Integer(), nullable=True))
    op.add_column('inverter_data', sa.Column('iac3', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inverter_data', 'iac3')
    op.drop_column('inverter_data', 'iac2')
    op.drop_column('inverter_data', 'iac1')
    # ### end Alembic commands ###
